name: "Basic Setup"
description: "Basic setup with pnpm and cache restore"
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node 22
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: "pnpm"

    - name: Add pnpm store path to env var
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Restore Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          **/node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
